// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTTYTzxUovf62S3QxbUtIO20OtWKqDXM',
    appId: '1:456451906355:web:df6340242449ff399c3c46',
    messagingSenderId: '456451906355',
    projectId: 'sangeetha-potha-app-flutter',
    authDomain: 'sangeetha-potha-app-flutter.firebaseapp.com',
    storageBucket: 'sangeetha-potha-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt4jqsJK0JxW1uYiOonh63AYQGfqXEJO0',
    appId: '1:456451906355:android:fabe26f0156b89189c3c46',
    messagingSenderId: '456451906355',
    projectId: 'sangeetha-potha-app-flutter',
    storageBucket: 'sangeetha-potha-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Ys30IraXnxvgRK7_u1FKCnj5HjFbcMo',
    appId: '1:456451906355:ios:2decd28fc78375799c3c46',
    messagingSenderId: '456451906355',
    projectId: 'sangeetha-potha-app-flutter',
    storageBucket: 'sangeetha-potha-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.sangeethaPothaAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Ys30IraXnxvgRK7_u1FKCnj5HjFbcMo',
    appId: '1:456451906355:ios:2decd28fc78375799c3c46',
    messagingSenderId: '456451906355',
    projectId: 'sangeetha-potha-app-flutter',
    storageBucket: 'sangeetha-potha-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.sangeethaPothaAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdTTYTzxUovf62S3QxbUtIO20OtWKqDXM',
    appId: '1:456451906355:web:7c0bafceec21ec209c3c46',
    messagingSenderId: '456451906355',
    projectId: 'sangeetha-potha-app-flutter',
    authDomain: 'sangeetha-potha-app-flutter.firebaseapp.com',
    storageBucket: 'sangeetha-potha-app-flutter.firebasestorage.app',
  );
}
